---
abstract: 'Graphing class hierarchies at run-time'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GraphViz-ISA
provides:
  GraphViz::ISA:
    file: lib/GraphViz/ISA.pm
    version: 1.100860
requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  GraphViz: 0
  Scalar::Util: 0
  Test::More: 0.88
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=GraphViz-ISA
  homepage: http://search.cpan.org/dist/GraphViz-ISA/
  repository: http://github.com/hanekomu/GraphViz-ISA
version: 1.100860
